<a href="https://colab.research.google.com/github/Matrixmax/Dive_into_DeepLearning/blob/main/0x00_tensor%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch


## 1.创建tensor

In [5]:
x = torch.empty(5,3)
print(x)


tensor([[7.6977e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.6323e-36]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.0012, 0.7837, 0.1374],
        [0.2017, 0.1614, 0.8177],
        [0.9012, 0.3619, 0.8841],
        [0.8289, 0.3633, 0.9065],
        [0.5360, 0.3352, 0.4287]])


In [7]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:

x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x) 


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2367,  0.2240,  0.6341],
        [ 2.1417,  0.5576,  0.1896],
        [ 0.4114, -0.9129, -1.7366],
        [ 0.0765, -0.0356,  0.2820],
        [-1.8124,  0.7957, -1.4066]])


In [10]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


## 2.tensor操作

### 2.1 算术操作

In [11]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.9399,  0.5442,  0.7103],
        [ 2.8612,  1.4721,  0.8289],
        [ 0.8528, -0.4052, -0.8559],
        [ 0.5521,  0.5211,  1.2597],
        [-0.9525,  1.5135, -1.4050]])


In [12]:
print(torch.add(x, y)) #另一种加法形式


tensor([[ 0.9399,  0.5442,  0.7103],
        [ 2.8612,  1.4721,  0.8289],
        [ 0.8528, -0.4052, -0.8559],
        [ 0.5521,  0.5211,  1.2597],
        [-0.9525,  1.5135, -1.4050]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.9399,  0.5442,  0.7103],
        [ 2.8612,  1.4721,  0.8289],
        [ 0.8528, -0.4052, -0.8559],
        [ 0.5521,  0.5211,  1.2597],
        [-0.9525,  1.5135, -1.4050]])


### 2.2 索引
我们还可以使用类似NumPy的索引操作来访问Tensor的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。**

In [14]:
print(x[0,:])
y = x[0,:]
y+=1
print(y)
print(x[0,:])  # 源tensor也被改了

tensor([0.2367, 0.2240, 0.6341])
tensor([1.2367, 1.2240, 1.6341])
tensor([1.2367, 1.2240, 1.6341])


### 2.3 改变形状
用view() 来改变形状

In [15]:
y = x.view(15)
z = x.view(-1,5) # -1所指的维度可以根据其他维度的值推出来
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)**

In [16]:
x += 1
print(x)
print(y) # 也加了1


tensor([[ 2.2367,  2.2240,  2.6341],
        [ 3.1417,  1.5576,  1.1896],
        [ 1.4114,  0.0871, -0.7366],
        [ 1.0765,  0.9644,  1.2820],
        [-0.8124,  1.7957, -0.4066]])
tensor([ 2.2367,  2.2240,  2.6341,  3.1417,  1.5576,  1.1896,  1.4114,  0.0871,
        -0.7366,  1.0765,  0.9644,  1.2820, -0.8124,  1.7957, -0.4066])


所以如果我们想返回一个真正新的副本（即不共享data内存）该怎么办呢？Pytorch还提供了一个reshape()可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用clone创造一个副本然后再使用view。

In [17]:
x_cp = x.clone().view(15)
x_=1
print(x)
print(x_cp)
print(x_cp.size())

tensor([[ 2.2367,  2.2240,  2.6341],
        [ 3.1417,  1.5576,  1.1896],
        [ 1.4114,  0.0871, -0.7366],
        [ 1.0765,  0.9644,  1.2820],
        [-0.8124,  1.7957, -0.4066]])
tensor([ 2.2367,  2.2240,  2.6341,  3.1417,  1.5576,  1.1896,  1.4114,  0.0871,
        -0.7366,  1.0765,  0.9644,  1.2820, -0.8124,  1.7957, -0.4066])
torch.Size([15])


另外一个常用的函数就是item(), 它可以将一个标量Tensor转换成一个Python number：

In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6508])
0.6507542133331299


## 3.广播机制

前面我们看到如何对两个形状相同的Tensor做按元素运算。当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。例如：

In [19]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)


tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


由于x和y分别是1行2列和3行1列的矩阵，如果要计算x + y，那么x中第一行的2个元素被广播（复制）到了第二行和第三行，而y中第一列的3个元素被广播（复制）到了第二列。如此，就可以对2个3行2列的矩阵按元素相加。

## 4.运算的内存开销

前面说了，索引操作是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [20]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
id_before = id(y)
y=y+x
print(id(y)==id_before)# False 

False


如果想指定结果到原来的y的内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把x + y的结果通过[:]写进y对应的内存中。

注：虽然view返回的Tensor与源Tensor是共享data的，但是依然是一个新的Tensor（因为Tensor除了包含data外还有一些其他属性），二者id（内存地址）并不一致。

In [21]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True


True


## 5.tensor和numpy的互相转换

我们很容易用numpy()和from_numpy()将Tensor和NumPy中的数组相互转换。但是需要注意的一点是： **这两个函数所产生的的Tensor和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！**

还有一个常用的将NumPy中的array转换成Tensor的方法就是torch.tensor(), 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的Tensor和原来的数据不再共享内存。

In [22]:
a = torch.ones(5)
b = a.numpy()
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [23]:
a+=1
print(a,b)
b+=1
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


numpy转tensor

使用from_numpy()将NumPy数组转换成Tensor:

In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [25]:
a+=1
print(a,b)
b+=1
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


此外上面提到还有一个常用的方法就是直接用torch.tensor()将NumPy数组转换成Tensor，需要注意的是该方法总是会进行数据拷贝，返回的Tensor和原来的数据不再共享内存。

In [26]:
c = torch.tensor(a)
a += 1
print(a,c)


[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 5.Tensor on GPU

用方法to()可以将Tensor在CPU和GPU（需要硬件支持）之间相互移动。

In [27]:
! /opt/bin/nvidia-smi

Tue Dec 22 14:25:05 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    33W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [28]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型


tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
